# Generated by Django 5.0.2 on 2024-02-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('peso', models.IntegerField()),
                ('unidade', models.CharField(choices=[(1, 'Kg'), (2, 'g')])),
                ('categoria', models.CharField()),
                ('quantidade', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
