# Generated by Django 5.0.2 on 2024-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedoces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doce',
            name='unidade',
            field=models.IntegerField(choices=[(1, 'Kg'), (2, 'g')]),
        ),
    ]
