# Generated by Django 5.0.2 on 2024-02-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedoces', '0003_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doce',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='sitedoces.categoria'),
        ),
    ]
